### ISSUE TITLE
Feature - Option to use title_pretty

### ISSUE THREAD

**Issue by soultaco83** [9-FS/nhentai_archivist#48]
I would llike to suggest if possible to use the Title_pretty as the name of the downloaded cbz files. 
So we would still have the ID but then the title_pretty following instead currently being the title_english
Maybe as an option that can be set in the .env file such as 

TITLE_TYPE = "TITLE_PRETTY"
but defaults to TITLE_ENGLISH if not set?

**Comment by soultaco83** [comment]
ended up creating a pull request
https://github.com/9-FS/nhentai_archivist/pull/49

**Comment by 9-FS** [comment]
I'm not really a fan of unnecessary complexity, but I guess we could do this if you really need this. Reason for `title_english` as filename was to have all the information necessary in the filename and the tags, depending on where you look. Also reliability and consistent behaviour because not every hentai has a `title_pretty`. Your solution is really janky though and I'm not going to approve this way, I'm going to leave some instructions for you. Generally speaking though, don't touch lines you don't need to touch, for example don't just remove comments from me willy nilly please...

**Comment by soultaco83** [comment]
Yeah i understand it is janky. I don't do much of this stuff and kinda winged it.
I had claude AI spot check my thinking and work around and I did not catch it removing your stuff. 
I'll get it all readded. Sorry about that.

**Comment by soultaco83** [comment]
@9-FS Looks like I only removed one comment from the config.rs file from what I can tell. Other than that, I am not sure how else I can optimize the search. The way I saw this working was one can enter Title_pretty into the config if they want it. If not it can default to title_english. My reason for this is that some files are having issues with the titles and folder names being so long it fails to move properly from a linux machine to a windows enviroment.

**Comment by 9-FS** [comment]
> My reason for this is that some files are having issues with the titles and folder names being so long it fails to move properly from a linux machine to a windows enviroment.

Ahh okay, that is a pretty legit reason. I'm personally running my instance on my Linux server, so I've never encountered that issue.

> The way I saw this working was one can enter Title_pretty into the config if they want it. If not it can default to title_english. 

This is basically fine with me, with some minor changes. See https://github.com/9-FS/nhentai_archivist/pull/49, I have left some instructions for you.

**Comment by soultaco83** [comment]
Pull request complete
