### ISSUE TITLE
Feature request: Allow us to specify .env file on the command line.

### ISSUE THREAD

**Issue by billsargent** [9-FS/nhentai_archivist#9]
I usually download by parody and would like to have a .env file for each parody that includes the correct tags and download location. Being able to specify the config file from the command line would be easier. 

Adding some command line options would also be good where some of the .env options are available from the command line for running in a script.

**Comment by 9-FS** [comment]
I currently have no plans to add command line capability.

Power users should use docker composes and the plan was to tell you that you could change environmental variables in the docker compose to overwrite or replace settings from your `./config/.env`. Well I just found out docker-compose does not support arrays for their environmental variables and I'm pretty miffed because I don't want to introduce a breaking change yet again.

I'll probably write a patch that allows for a comma separated input in the `docker-compose.yaml`.

**Comment by 9-FS** [comment]
Opened issue #13 to fix the bug. This issue will be closed, because I currently don't plan to support command line capability.
